package com.example.sohaengsung.ui.navigation

object ScreenRoute {
    const val LOGIN = "login"
    const val EMAIL_LOGIN = "email-login"
    const val KAKAO_LOGIN = "kakao-login"
    const val SIGN_UP = "sign-up"
    const val HOME = "home"
    const val PLACE_RECOMMEND = "place-recommend"
    const val PATH_RECOMMEND = "path-recommend"
    const val BOOKMARK = "bookmark"
    const val SETTING = "setting"
    const val LEVEL = "level"
    const val LEVEL_INFO = "level-info"
    const val ACCOUNT_MANAGEMENT = "account-management"
    const val THEME_CHANGE = "theme-change"
    const val TERMS = "terms"
    const val NOTICE = "notice"
    const val MAP = "map"
    const val COUPON = "coupon"
    const val VOUCHER = "voucher"
    const val REVIEW = "review"
    const val EVENT = "event"
    const val MAP_PATH_RECOMMEND = "map-path-recommend"
}